[theme]
primaryColor = "#6eb52f"
backgroundColor = "#f0f0f5"
secondaryBackgroundColor = "#e0e0ef"
textColor = "#262730"
font = "sans serif"

[pages]
  [pages.accueil]
  path = "tableau_de_bord/1_ACCUEIL.py"
  name = "Accueil"

  [pages.tableau]
  path = "tableau_de_bord/2_TABLEAU_DE_BORD.py"
  name = "Tableau_de_bord"

  [pages.desordres]
  path = "3_DESORDRES.py"
  name = "Desordres"

  [pages.prestations]
  path = "tableau_de_bord/4_PRESTATIONS.py"
  name = "Prestations"

  [pages.reseaux]
  path = "tableau_de_bord/5_RESEAUX.py"
  name = "Reseaux"

  [pages.parametres]
  path = "tableau_de_bord/6_PARAMETRES.py"
  name = "Parametres"
